### ISSUE TITLE
Does this library works for ios also?

### ISSUE THREAD

**Issue by dusanspasojevic** [Nilsantos/react-native-screen-audio-recorder#4]
Does this library works for ios also?
Because on ios I get an error that AudioRecorder.init is not a fuction and that it is undefined.

**Comment by Nilsantos** [comment]
For now it only works for android, sorry.

**Comment by dusanspasojevic** [comment]
Thanks for answering, so what do you think that would be the best way to do
that, should I write my native code for ios and is it even possible to
record internal audio on ios?

пон, 2. мај 2022. у 16:33 Danilo Santos ***@***.***> је
написао/ла:

**Comment by dusanspasojevic** [comment]
Thanks for answering, so what do you think that would be the best way to do
that, should I write my native code for ios and is it even possible to
record internal audio on ios?

**Comment by Nilsantos** [comment]
I was searching and I think it is possible to record internal audio on ios. If you do and want to share native code, it would be awesome to use in this library.

**Comment by dusanspasojevic** [comment]
If I manage to make it work I'll share it to you.

**Comment by Nilsantos** [comment]
Thank you so much @dusanspasojevic!
